create table produtoCategoria (
     id integer generated by default as identity,
     dataCadastro timestamp default CURRENT_TIMESTAMP,
     nome varchar(255),
     obs varchar(255),
     habilitado boolean not null default 1,
     primary key (id)
);