create table produto (
     id integer generated by default as identity,
     dataCadastro timestamp default CURRENT_TIMESTAMP,
     nome varchar(255),
     valor double,
     quantidade integer,
     produtoTipoId integer,
     produtoCategoriaId integer,
     obs varchar(255),
     habilitado boolean not null default 1,
     primary key (id)
);

alter table produto 
   add constraint fk_produto_Tipo
   foreign key (produtoTipoId)
   references tipoProduto;
   
alter table produto 
   add constraint fk_produto_Categoria
   foreign key (produtoCategoriaId)
   references tipoCategoria;